name: Build Release DLL

on:
  push:
    branches: [build-clang, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan==2.18.1

      - name: Setup Conan profile
        run: |
          conan profile detect --force

      - name: Install dependencies
        run: |
          conan install . --profile=profiles/clang-win32 -o libcurl/*:with_ssl=False --build=missing

      - name: Apply ECFMP fixes
        run: |
          git apply --verbose --directory=third_party/ecfmp ecfmp-complete-fixes.patch
        shell: powershell

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake with ECFMP enabled
        run: |
          cmake --preset conan-default -DENABLE_ECFMP=ON

      - name: Build all targets
        id: build_all
        run: |
          Write-Host "🔨 Building all targets with ECFMP enabled..."

          # Build all targets in one command
          cmake --build build --config Release

          # Verify DLL was built
          if (Test-Path "build/bin/UKControllerPluginCore.dll") {
            Write-Host "✅ UKControllerPluginCore.dll built successfully"
            echo "plugin_built=true" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "❌ UKControllerPluginCore.dll build failed"
            echo "plugin_built=false" >> $env:GITHUB_OUTPUT
            exit 1
          }
        shell: pwsh

      - name: Upload DLL artifact (if successful)
        if: steps.build_all.outputs.plugin_built == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: uk-controller-plugin-dll
          path: build/bin/UKControllerPluginCore.dll

      - name: Upload utility libraries
        uses: actions/upload-artifact@v4
        with:
          name: uk-controller-plugin-utils
          path: |
            build/lib/UKControllerPluginUtils.lib
            build/lib/UKControllerPluginTestingUtils.lib

      - name: Report build status
        run: |
          if (${{ steps.build_all.outputs.plugin_built == 'true' }}) {
            Write-Host "🎉 Complete build successful - DLL, utilities, and ECFMP features ready!"
            Write-Host "📦 Built with ECFMP SDK enabled for full flow measure functionality"
          } else {
            Write-Host "❌ Build failed - check logs for details"
          }
        shell: pwsh
