name: Build Release DLL

on:
  push:
    branches: [build-clang, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan==2.18.1

      - name: Setup Conan profile
        run: |
          conan profile detect --force

      - name: Install dependencies
        run: |
          conan install . --profile=profiles/clang-win32 -o libcurl/*:with_ssl=False --build=missing

      - name: Apply ECFMP fixes
        run: |
          git apply --verbose --directory=third_party/ecfmp ecfmp-complete-fixes.patch
        shell: pwsh

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake with ECFMP enabled
        run: |
          cmake --preset conan-default -DENABLE_ECFMP=ON

      - name: Build all targets
        id: build_all
        run: |
          cmake --build build --config Release
        shell: pwsh

      - name: Upload DLL artifact (if successful)
        uses: actions/upload-artifact@v4
        with:
          name: uk-controller-plugin-dll
          path: build/bin/UKControllerPluginCore.dll

      - name: Upload utility libraries
        uses: actions/upload-artifact@v4
        with:
          name: uk-controller-plugin-utils
          path: |
            build/lib/UKControllerPluginUtils.lib
            build/lib/UKControllerPluginTestingUtils.lib
