name: Build Release DLL

on:
  push:
    branches: [build-clang, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Clang
        run: |
          # Check if LLVM is already installed, if not install it
          if (!(Get-Command clang-cl -ErrorAction SilentlyContinue)) {
              # Install latest LLVM/Clang which includes clang-cl
              choco install llvm -y
          } else {
              Write-Host "LLVM/Clang is already installed"
              clang-cl --version
          }
          # Add to PATH for this session
          echo "C:\Program Files\LLVM\bin" >> $env:GITHUB_PATH
        shell: powershell

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan==2.18.1

      - name: Setup Conan profile
        run: |
          conan profile detect --force

      - name: Install dependencies
        run: |
          conan install . --profile=profiles/clang-win32 -o libcurl/*:with_ssl=False --build=missing

      - name: Apply ECFMP fixes
        run: |
          Write-Host "🔧 Applying ECFMP SDK fixes for clang-cl compatibility..."
          cd third_party/ecfmp

          # Apply the patch (ignore errors if already applied)
          try {
              git apply --ignore-whitespace ../../ecfmp-complete-fixes.patch *>$null
              Write-Host "✅ ECFMP patch applied successfully"
          } catch {
              Write-Host "ℹ️ Patch not applied (may already be applied) - continuing with build..."
          }

          # Verify critical files have the fixes we need
          $eventBusContent = Get-Content "include/ECFMP/eventbus/EventBus.h" -Raw
          if ($eventBusContent -like "*protected:*GetStream*") {
              Write-Host "✅ EventBus.h fix confirmed"
          } else {
              Write-Host "❌ EventBus.h fix missing - applying manually..."
              (Get-Content "include/ECFMP/eventbus/EventBus.h") -replace "        private:", "        protected:" | Set-Content "include/ECFMP/eventbus/EventBus.h"
          }
        shell: powershell

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Configure CMake with ECFMP enabled
        run: |
          cmake --preset conan-default -DENABLE_ECFMP=ON

      - name: Build all targets
        id: build_all
        run: |
          Write-Host "🔨 Building all targets with ECFMP enabled..."

          # Build utilities
          cmake --build build --config Release --target UKControllerPluginUtils
          cmake --build build --config Release --target UKControllerPluginTestingUtils

          # Build main plugin DLL (should work with our patches)
          cmake --build build --config Release --target UKControllerPluginCore

          # Build tests (if available)
          cmake --build build --config Release --target UKControllerPluginTest -ErrorAction Continue

          # Verify DLL was built
          if (Test-Path "build/bin/UKControllerPluginCore.dll") {
            Write-Host "✅ UKControllerPluginCore.dll built successfully"
            echo "plugin_built=true" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "❌ UKControllerPluginCore.dll build failed"
            echo "plugin_built=false" >> $env:GITHUB_OUTPUT
            exit 1
          }
        shell: pwsh

      - name: Upload DLL artifact (if successful)
        if: steps.build_all.outputs.plugin_built == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: uk-controller-plugin-dll
          path: build/bin/UKControllerPluginCore.dll

      - name: Upload utility libraries
        uses: actions/upload-artifact@v4
        with:
          name: uk-controller-plugin-utils
          path: |
            build/lib/UKControllerPluginUtils.lib
            build/lib/UKControllerPluginTestingUtils.lib

      - name: Report build status
        run: |
          if (${{ steps.build_all.outputs.plugin_built == 'true' }}) {
            Write-Host "🎉 Complete build successful - DLL, utilities, and ECFMP features ready!"
            Write-Host "📦 Built with ECFMP SDK enabled for full flow measure functionality"
          } else {
            Write-Host "❌ Build failed - check logs for details"
          }
        shell: pwsh
